# Generated by Django 5.2.3 on 2025-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taskmodel',
            fields=[
                ('Task_id', models.AutoField(primary_key=True, serialize=False)),
                ('Task_title', models.CharField(max_length=100)),
                ('Task_description', models.CharField(max_length=300)),
                ('Task_priority', models.CharField(choices=[('All', 'All'), ('Aditya', 'Aditya'), ('Nishant', 'Nishant'), ('Vibhavavi', 'Vibhavavi')], max_length=200)),
                ('Start_date', models.DateField(auto_now_add=True)),
                ('End_date', models.DateField(auto_now=True)),
                ('Task_type', models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('Accounts', 'Accounts')], max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
