# Generated by Django 5.2.3 on 2025-11-07 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('Manager_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leaveid', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('SL', 'SL'), ('CL', 'CL'), ('PL', 'PL'), ('LWP', 'LWP')], max_length=100)),
                ('reason', models.CharField(default='Leave reason', max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('total_days', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=200)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approved', to='App1.employee')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_applied', to='App1.manager'),
        ),
    ]
