# Generated by Django 5.2.3 on 2025-11-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Managermodel',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employeemodel',
        ),
        migrations.CreateModel(
            name='Leavemodel',
            fields=[
                ('leaveid', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('SL', 'SL'), ('CL', 'CL'), ('PL', 'PL'), ('LWP', 'LWP')], max_length=100)),
                ('reason', models.CharField(default='Leave reason', max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('total_days', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=200)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approved', to='App1.employeemodel')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.employeemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
