# Generated by Django 5.2.3 on 2025-10-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.CharField(max_length=20)),
                ('Role_Name', models.CharField(max_length=50)),
                ('Role_Description', models.CharField(max_length=100)),
            ],
        ),
    ]
