# Generated by Django 5.2.3 on 2025-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsmodel',
            name='SrNo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
