# Generated by Django 5.2.3 on 2025-11-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('Review_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Review_Title', models.CharField(max_length=100)),
                ('Select_Employee', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('TL', 'TL')], max_length=100)),
                ('Review_Date', models.DateField(auto_now_add=True)),
                ('Review_Period', models.CharField(choices=[('Month', 'Month'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=100)),
                ('Enter_Rating', models.IntegerField()),
                ('Comment', models.CharField(blank=True, max_length=300, null=True)),
                ('Created_by', models.DateTimeField(auto_now_add=True)),
                ('Updated_by', models.DateTimeField(auto_now=True)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_as_employee', to='App.employee')),
                ('Reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_as_reviewer', to='App.employee')),
            ],
            options={
                'db_table': 'receive',
            },
        ),
    ]
