# Generated by Django 5.2.3 on 2025-11-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receive',
            new_name='Review',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
