# Generated by Django 5.2.3 on 2025-11-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App1', '0002_rename_manager_managermodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Quota',
            fields=[
                ('quotaid', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('sick leave', 'sick leave'), ('casual leave', 'casual leave'), ('PL', 'PL'), ('LWP', 'LWP')], max_length=100)),
                ('total_quota', models.IntegerField()),
                ('used_quota', models.IntegerField()),
                ('remain_quota', models.IntegerField()),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.employeemodel')),
            ],
        ),
    ]
