# Generated by Django 5.2.3 on 2025-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('SrNo', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=255)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Team Leader', 'Team Leader'), ('Employee', 'Employee')], max_length=100)),
                ('Department', models.CharField(choices=[('Operation', 'Operation'), ('Sales', 'Sales'), ('Accounts', 'Accounts'), ('IT', 'IT')], max_length=100)),
                ('Date_of_Joining', models.DateField(auto_now=True)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
