# Generated by Django 5.2.3 on 2025-10-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_employee_id_alter_employee_srno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='SrNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
