# Generated by Django 5.2.3 on 2025-10-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_employee_id_alter_employee_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='SrNo',
            field=models.IntegerField(),
        ),
    ]
